const BRIDGE_URL=`${SUPABASE_URL}/functions/v1/admin-support-bridge`;
const $=id=>document.getElementById(id);let users=[],filter='all';
const esc=v=>String(v??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const token=()=>localStorage.getItem('admin_bridge_token')||'';
async function call(action,extra={}){const r=await fetch(BRIDGE_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token()}`},body:JSON.stringify({action,...extra})});let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||`Support service error ${r.status}`);return d}
const nameOf=(p,id)=>p?.fullname||p?.full_name||p?.name||('User '+String(id||'').slice(0,6));
async function load(){if(!$('list'))return;$('list').innerHTML='<div class="empty loading">Loading conversations…</div>';try{const d=await call('list'),rows=d.messages||[],pm=new Map((d.profiles||[]).map(p=>[p.id,p])),map=new Map();for(const r of rows){if(!r.user_id)continue;let g=map.get(r.user_id);if(!g)g={user_id:r.user_id,profile:pm.get(r.user_id)||null,messages:[],latest:r,needs:false};g.messages.push(r);if(new Date(r.created_at)>new Date(g.latest.created_at))g.latest=r;if(r.status==='open'&&!r.admin_reply)g.needs=true;map.set(r.user_id,g)}users=[...map.values()].sort((a,b)=>new Date(b.latest.created_at)-new Date(a.latest.created_at));render()}catch(e){console.error(e);$('list').innerHTML='<div class="empty error">Support could not be loaded.<br><small>'+esc(e.message)+'</small></div>';users=[];$('counter').textContent='0 users';$('subcount').textContent='0 conversations'}}
function render(){const q=$('search').value.toLowerCase().trim();const out=users.filter(u=>{const p=u.profile||{},text=(nameOf(p,u.user_id)+' '+(p.email||'')+' '+(p.phone||'')+' '+u.user_id+' '+u.messages.map(m=>m.message||m.admin_reply||'').join(' ')).toLowerCase();return(!q||text.includes(q))&&(filter==='all'||(filter==='open'&&u.needs)||(filter==='read'&&!u.needs))});$('counter').textContent=users.length+' users';$('subcount').textContent=out.length+' conversations';if(!out.length){$('list').innerHTML='<div class="empty">No conversations found.</div>';return}$('list').innerHTML=out.map(u=>{const n=nameOf(u.profile,u.user_id),latest=u.latest;return `<article class="conversation" onclick="openConversation('${esc(u.user_id)}')"><div class="avatar">${esc(n.charAt(0).toUpperCase())}</div><div class="details"><p class="name">${esc(n)}</p><p class="preview">${esc(latest.message||latest.admin_reply||'No message')}</p></div><div class="meta"><span class="time">${new Date(latest.created_at).toLocaleString()}</span><span class="pill ${u.needs?'unread':''}">${u.needs?'NEEDS REPLY':u.messages.length+' MESSAGES'}</span></div></article>`}).join('')}
window.openConversation=id=>{localStorage.setItem('selectedSupportUser',id);location.href='admin-chat.html'};
$('search')?.addEventListener('input',render);$('refresh')?.addEventListener('click',load);document.querySelectorAll('.filters button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()}));load();setInterval(load,30000);