const db=window.supabaseClient;
const userId=localStorage.getItem('selectedSupportUser');
let sending=false;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
if($('backBtn'))$('backBtn').onclick=()=>window.location.href='admin-support.html';
document.addEventListener('DOMContentLoaded',()=>{if(!userId){window.location.href='admin-support.html';return}loadChat()});
async function loadChat(){try{const r=await db.from('support_messages').select('id,user_id,message,admin_reply,status,created_at').eq('user_id',userId).order('created_at',{ascending:true});if(r.error)throw r.error;const messages=r.data||[];if(!messages.length){$('userName').textContent='User';$('chatStatus').textContent='No messages';$('chatContainer').innerHTML='<div class="loading">No messages yet.</div>';return}let name='User '+userId.slice(0,8);const p=await db.from('profiles').select('fullname,email,phone').eq('id',userId).maybeSingle();if(!p.error&&p.data?.fullname)name=p.data.fullname;$('userName').textContent=name;$('avatar').textContent=name.charAt(0).toUpperCase();$('chatStatus').textContent=messages.some(m=>m.status==='open'&&!m.admin_reply)?'Needs reply':'Conversation';const chat=$('chatContainer');chat.innerHTML='';for(const m of messages){if(m.message)chat.innerHTML+=`<div class="user-message">${esc(m.message)}<div class="message-time">${new Date(m.created_at).toLocaleString()}</div></div>`;if(m.admin_reply)chat.innerHTML+=`<div class="admin-message">${esc(m.admin_reply)}<div class="message-time">MDH Support · ${new Date(m.created_at).toLocaleString()}</div></div>`}chat.scrollTop=chat.scrollHeight}catch(e){console.error('Admin chat load failed',e);$('userName').textContent='Unable to load conversation';$('chatStatus').textContent=e.message||'Support error'}}
if($('sendBtn'))$('sendBtn').addEventListener('click',sendReply);if($('replyInput'))$('replyInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendReply()}});
async function sendReply(){if(sending)return;const input=$('replyInput'),reply=input.value.trim();if(!reply||!userId)return;sending=true;$('sendBtn').disabled=true;try{const r=await db.from('support_messages').select('id').eq('user_id',userId).is('admin_reply',null).order('created_at',{ascending:false}).limit(1);if(r.error)throw r.error;if(!r.data?.length){$('chatStatus').textContent='No unanswered message';return}const u=await db.from('support_messages').update({admin_reply:reply,status:'closed'}).eq('id',r.data[0].id);if(u.error)throw u.error;const n=await db.from('user_notifications').insert({user_id:userId,title:'Support Reply',message:reply,type:'support',is_read:false,created_at:new Date().toISOString()});if(n.error)console.warn('Notification failed',n.error);input.value='';await loadChat()}catch(e){console.error('Admin reply failed',e);alert('Failed to send reply. Please try again.')}finally{sending=false;$('sendBtn').disabled=false}}
setInterval(loadChat,10000);