const db=window.supabaseClient;let currentUser=null,profile=null;
document.addEventListener('DOMContentLoaded',async()=>{try{if(!db)throw new Error('Supabase client not initialized');const{data:{user},error:authError}=await db.auth.getUser();if(authError)throw authError;if(!user){location.href='login.html';return}currentUser=user;try{if(typeof checkMiningIncome==='function')await checkMiningIncome()}catch(e){console.warn('Mining income check skipped:',e)}await initializeProfile()}catch(e){console.error('Profile initialization failed:',e);const name=document.getElementById('userName');if(name)name.textContent='Unable to load profile'}});
async function initializeProfile(){await loadProfile();await Promise.allSettled([loadStatistics(),loadNotifications()])}
async function loadProfile(){const{data,error}=await db.from('profiles').select('*').eq('id',currentUser.id).maybeSingle();if(error){console.error('Profile query failed:',error);return}profile=data||{};const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};set('userName','Welcome, '+(profile.fullname||'User'));set('fullName',profile.fullname||'User');set('email',profile.email||currentUser.email||'No Email');set('walletBalance','UGX '+Number(profile.wallet_balance||0).toLocaleString());set('membership',profile.membership||'Standard');set('kycStatus',profile.kyc_status||'Not Verified');set('accountStatus',profile.account_status||'Active');if(profile.avatar_url){const avatar=document.getElementById('avatar');if(avatar)avatar.src=profile.avatar_url)}}
async function loadStatistics(){if(!profile)return;const[machineResult,teamResult]=await Promise.allSettled([db.from('user_machines').select('id').eq('user_id',currentUser.id).eq('status','active'),db.from('referrals').select('id').eq('referrer_id',currentUser.id)]);const machines=machineResult.status==='fulfilled'?machineResult.value.data:null;const team=teamResult.status==='fulfilled'?teamResult.value.data:null;const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};set('activeMachines',machines?.length||0);set('teamMembers',team?.length||0);set('referralBonus','UGX '+Number(profile.total_referral_bonus||0).toLocaleString());const code=String(profile.referral_code||'').trim();const codeEl=document.getElementById('referralCode');const linkEl=document.getElementById('referralLink');if(codeEl){codeEl.value=code||'No referral code yet';codeEl.placeholder=code?'':'No referral code yet'}if(linkEl){linkEl.value=code?new URL('register.html?ref='+encodeURIComponent(code),location.href).href:'Referral link unavailable';linkEl.placeholder=code?'':'Referral link unavailable'}}
async function loadNotifications(){if(!currentUser)return;const{data,error}=await db.from('user_notifications').select('id').eq('user_id',currentUser.id).eq('is_read',false);if(error){console.warn('Unread notification query failed:',error);return}const total=data?.length||0;['notifyCount','notificationCount'].forEach(id=>{const el=document.getElementById(id);if(!el)return;el.textContent=String(total);el.style.display=total>0?'flex':'none';el.setAttribute('aria-label',total+' unread notifications')})}
setInterval(async()=>{if(!currentUser)return;try{await loadProfile();await loadStatistics();await loadNotifications()}catch(e){console.warn('Profile refresh failed:',e)}},30000);
async function copyText(value,message){if(!value||value.startsWith('No referral'))return;try{await navigator.clipboard.writeText(value);toast(message)}catch(e){console.error(e)}}function toast(message){const t=document.createElement('div');t.className='mdh-toast';t.textContent=message;document.body.appendChild(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),220)},1800)}
document.getElementById('copyReferral')?.addEventListener('click',()=>copyText(document.getElementById('referralCode')?.value,'Referral code copied'));
document.getElementById('shareReferral')?.addEventListener('click',async()=>{const link=document.getElementById('referralLink')?.value||'';if(!link||link.startsWith('Referral link'))return;if(navigator.share){try{await navigator.share({title:'Marathon Digital Hub',text:'Join my Marathon Digital Hub team.',url:link})}catch(e){if(e.name!=='AbortError')console.error(e)}}else await copyText(link,'Referral link copied')});
document.getElementById('changePhoto')?.addEventListener('click',()=>document.getElementById('photoInput')?.click());document.getElementById('photoInput')?.addEventListener('change',uploadPhoto);
async function uploadPhoto(e){const file=e.target.files?.[0];if(!file||!currentUser)return;const name=currentUser.id+'-'+Date.now();const{error}=await db.storage.from('machine-images').upload(name,file,{upsert:true});if(error){toast(error.message);return}const{data}=db.storage.from('machine-images').getPublicUrl(name);const{error:updateError}=await db.from('profiles').update({avatar_url:data.publicUrl}).eq('id',currentUser.id);if(updateError){toast('Photo could not be saved');console.error(updateError);return}const avatar=document.getElementById('avatar');if(avatar)avatar.src=data.publicUrl;toast('Profile photo updated')}
document.getElementById('logoutBtn')?.addEventListener('click',async()=>{await db.auth.signOut();location.href='login.html'});