const db=window.supabaseClient;const $=id=>document.getElementById(id);let members=[],currentFilter='all',refLink='';
function money(v){return'UGX '+Number(v||0).toLocaleString()}
function statusOf(m){const active=String(m.account_status||'').toLowerCase()==='active';const verified=String(m.kyc_status||'').toLowerCase()==='verified'||m.email_verified===true||m.phone_verified===true;return{active,verified}}
function render(){const list=$('teamList');const filtered=members.filter(m=>currentFilter==='all'?true:currentFilter==='active'?statusOf(m).active:currentFilter==='inactive'&&!statusOf(m).active:currentFilter==='unverified'&&!statusOf(m).verified);if(!filtered.length){list.innerHTML='<div class="empty">No members in this category yet.</div>';return}list.innerHTML=filtered.map(m=>{const s=statusOf(m),state=s.active?'ACTIVE':!s.verified?'UNVERIFIED':'INACTIVE';return`<div class="team-member"><div class="avatar">${(m.fullname||'U').charAt(0).toUpperCase()}</div><main><h4>${m.fullname||'MDH Member'}</h4><p>${m.membership||'Standard'} • Joined ${m.created_at?new Date(m.created_at).toLocaleDateString():'Recently'}</p></main><span class="member-status ${state.toLowerCase()}">${state}</span></div>`}).join('')}
function setupQR(){const modal=$('qrModal'),box=$('referralQR');if(!modal||!box||!$('openQR'))return;$('openQR').onclick=()=>{if(!refLink)return;box.innerHTML='';new QRCode(box,{text:refLink,width:210,height:210,colorDark:'#19e889',colorLight:'#062a23',correctLevel:QRCode.CorrectLevel.H});$('qrCodeLabel').textContent=$('referralCode').textContent;modal.classList.add('show');modal.setAttribute('aria-hidden','false')};$('closeQR').onclick=()=>{modal.classList.remove('show');modal.setAttribute('aria-hidden','true')};modal.onclick=e=>{if(e.target===modal)$('closeQR').click()};$('downloadQR').onclick=()=>{const canvas=box.querySelector('canvas'),img=box.querySelector('img'),src=canvas?canvas.toDataURL('image/png'):img?.src;if(!src)return;const a=document.createElement('a');a.href=src;a.download='MDH-'+$('referralCode').textContent+'-QR.png';a.click()}}
async function load(){const codeEl=$('referralCode'),linkEl=$('referralLink'),teamEl=$('teamList');try{codeEl.textContent='Connecting...';linkEl.textContent='Connecting...';teamEl.innerHTML='<div class="empty">Connecting to referral data...</div>';if(!db)throw new Error('Supabase client not initialized');const{data:{user},error:authError}=await db.auth.getUser();if(authError)throw authError;if(!user){location.href='login.html';return}
const{data:profile,error:profileError}=await db.rpc('get_my_referral_info');if(profileError)throw profileError;if(!profile?.referral_code)throw new Error('Referral code not found');const code=String(profile.referral_code).trim();codeEl.textContent=code;refLink=new URL('register.html?ref='+encodeURIComponent(code),location.href).href;linkEl.textContent=refLink;const wa=$('whatsappShare');if(wa)wa.href='https://wa.me/?text='+encodeURIComponent('Join me on Marathon Digital Hub: '+refLink);$('bonus').textContent=money(profile.total_referral_bonus);setupQR();
// Team statistics are best-effort. A restrictive RLS policy must not prevent the user's own code/link from loading.
const{data:team,error:teamError}=await db.from('profiles').select('id,fullname,membership,account_status,email_verified,phone_verified,kyc_status,created_at').eq('referred_by',code).order('created_at',{ascending:false});if(teamError){console.warn('Referral team:',teamError);members=[]}else members=team||[];const active=members.filter(m=>statusOf(m).active).length;const verified=members.filter(m=>statusOf(m).verified).length;$('teamCount').textContent=members.length;$('activeReferrals').textContent=active;$('activeCount').textContent=active;$('allCount').textContent=members.length;$('inactiveCount').textContent=members.length-active;$('unverifiedCount').textContent=members.length-verified;render()}catch(e){console.error('Referral load:',e);codeEl.textContent='Unavailable';linkEl.textContent='Refresh page';teamEl.innerHTML='<div class="empty">Referral data could not be loaded. Please refresh or contact support.</div>'}}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()});
$('copyCode').onclick=async()=>{const v=$('referralCode').textContent;if(!v||v==='Connecting...'||v==='Unavailable')return;try{await navigator.clipboard.writeText(v);$('copyCode').textContent='Copied!'}catch(e){$('copyCode').textContent='Copy failed'}setTimeout(()=>$('copyCode').textContent='Copy',1200)};
$('copyLink').onclick=async()=>{const v=$('referralLink').textContent;if(!v||v==='Connecting...'||v==='Unavailable'||v==='Refresh page')return;try{await navigator.clipboard.writeText(v);$('copyLink').textContent='Copied!'}catch(e){$('copyLink').textContent='Copy failed'}setTimeout(()=>$('copyLink').textContent='Copy',1200)};
$('shareReferral').onclick=async()=>{if(!refLink)return;const text='Join me on Marathon Digital Hub: '+refLink;if(navigator.share)try{await navigator.share({title:'Marathon Digital Hub',text,url:refLink})}catch(e){}else{try{await navigator.clipboard.writeText(text);$('shareReferral').textContent='Copied Invite!';setTimeout(()=>$('shareReferral').textContent='↗ Share Invite',1500)}catch(e){}}};
load();