const db=window.supabaseClient;const $=id=>document.getElementById(id);let members=[],currentFilter='all',refLink='';
function money(v){return'UGX '+Number(v||0).toLocaleString()}
function statusOf(m){const active=String(m.account_status||'').toLowerCase()==='active';const verified=String(m.kyc_status||'').toLowerCase()==='verified'||m.email_verified===true||m.phone_verified===true;return{active,verified}}
function render(){const list=$('teamList');if(!list)return;const filtered=members.filter(m=>currentFilter==='all'?true:currentFilter==='active'?statusOf(m).active:currentFilter==='inactive'&&!statusOf(m).active:currentFilter==='unverified'&&!statusOf(m).verified);if(!filtered.length){list.innerHTML='<div class="empty">No members in this category yet.</div>';return}list.innerHTML=filtered.map(m=>{const s=statusOf(m),state=s.active?'ACTIVE':!s.verified?'UNVERIFIED':'INACTIVE';return`<div class="team-member"><div class="avatar">${(m.fullname||'U').charAt(0).toUpperCase()}</div><main><h4>${m.fullname||'MDH Member'}</h4><p>${m.membership||'Standard'} • Joined ${m.created_at?new Date(m.created_at).toLocaleDateString():'Recently'}</p></main><span class="member-status ${state.toLowerCase()}">${state}</span></div>`}).join('')}
function setupQR(){const modal=$('qrModal'),box=$('referralQR'),open=$('openQR');if(!modal||!box||!open)return;open.onclick=()=>{if(!refLink)return;box.innerHTML='';if(typeof QRCode==='undefined'){alert('QR code is still loading. Please try again.');return}new QRCode(box,{text:refLink,width:210,height:210,colorDark:'#19e889',colorLight:'#062a23',correctLevel:QRCode.CorrectLevel.H});const label=$('qrCodeLabel');if(label)label.textContent=$('referralCode')?.textContent||'';modal.classList.add('show');modal.setAttribute('aria-hidden','false')};if($('closeQR'))$('closeQR').onclick=()=>{modal.classList.remove('show');modal.setAttribute('aria-hidden','true')};modal.onclick=e=>{if(e.target===modal&&$('closeQR'))$('closeQR').click()};if($('downloadQR'))$('downloadQR').onclick=()=>{const canvas=box.querySelector('canvas'),img=box.querySelector('img'),src=canvas?canvas.toDataURL('image/png'):img?.src;if(!src)return;const a=document.createElement('a');a.href=src;a.download='MDH-'+($('referralCode')?.textContent||'Referral')+'-QR.png';a.click()}}
async function withTimeout(promise,ms){return await Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Request timeout')),ms))])}
async function ensureSession(){let r=await withTimeout(db.auth.getSession(),8000);if(r.data?.session)return r.data.session;try{r=await withTimeout(db.auth.refreshSession(),8000);if(r.data?.session)return r.data.session}catch(e){console.warn('Session refresh:',e)}return null}
async function getReferralProfile(userId){let rpcError=null;try{const r=await withTimeout(db.rpc('get_my_referral_info'),8000);if(!r.error&&r.data?.referral_code)return r.data;rpcError=r.error||new Error('Referral RPC returned no code')}catch(e){rpcError=e}try{const r=await withTimeout(db.from('profiles').select('id,fullname,email,wallet_balance,membership,kyc_status,account_status,total_referral_bonus,referral_code').eq('id',userId).maybeSingle(),8000);if(!r.error&&r.data?.referral_code)return r.data}catch(e){console.warn('Profile referral fallback:',e)}throw rpcError||new Error('Referral code not found')}
async function loadTeam(code){try{const r=await withTimeout(db.from('profiles').select('id,fullname,membership,account_status,email_verified,phone_verified,kyc_status,created_at').eq('referred_by',code).order('created_at',{ascending:false}),8000);if(!r.error)return r.data||[];console.warn('Referral team:',r.error)}catch(e){console.warn('Referral team:',e)}return[]}
async function load(){const codeEl=$('referralCode'),linkEl=$('referralLink'),teamEl=$('teamList');try{if(codeEl)codeEl.textContent='Connecting...';if(linkEl)linkEl.textContent='Connecting...';if(teamEl)teamEl.innerHTML='<div class="empty">Connecting to referral data...</div>';if(!db)throw new Error('Supabase client not initialized');const session=await ensureSession();if(!session){const{data:{user},error}=await withTimeout(db.auth.getUser(),8000);if(error)throw error;if(!user){location.href='login.html';return}const profile=await getReferralProfile(user.id);return finish(profile,codeEl,linkEl,teamEl)}const profile=await getReferralProfile(session.user.id);return finish(profile,codeEl,linkEl,teamEl)}catch(e){console.error('Referral load:',e);if(codeEl)codeEl.textContent='Unavailable';if(linkEl)linkEl.textContent='Refresh page';if(teamEl)teamEl.innerHTML='<div class="empty">Referral data could not be loaded. Please refresh or contact support.</div>'}}
async function finish(profile,codeEl,linkEl,teamEl){const code=String(profile.referral_code||'').trim();if(!code)throw new Error('Referral code not found');if(codeEl)codeEl.textContent=code;refLink=new URL('register.html?ref='+encodeURIComponent(code),location.href).href;if(linkEl)linkEl.textContent=refLink;const wa=$('whatsappShare');if(wa)wa.href='https://wa.me/?text='+encodeURIComponent('Join me on Marathon Digital Hub: '+refLink);if($('bonus'))$('bonus').textContent=money(profile.total_referral_bonus);try{setupQR()}catch(e){console.warn('QR setup:',e)}members=await loadTeam(code);const active=members.filter(m=>statusOf(m).active).length;const verified=members.filter(m=>statusOf(m).verified).length;if($('teamCount'))$('teamCount').textContent=members.length;if($('activeReferrals'))$('activeReferrals').textContent=active;if($('activeCount'))$('activeCount').textContent=active;if($('allCount'))$('allCount').textContent=members.length;if($('inactiveCount'))$('inactiveCount').textContent=members.length-active;if($('unverifiedCount'))$('unverifiedCount').textContent=members.length-verified;render()}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()});
if($('copyCode'))$('copyCode').onclick=async()=>{const v=$('referralCode')?.textContent;if(!v||v==='Connecting...'||v==='Unavailable')return;try{await navigator.clipboard.writeText(v);$('copyCode').textContent='Copied!'}catch(e){$('copyCode').textContent='Copy failed'}setTimeout(()=>$('copyCode').textContent='Copy',1200)};
if($('copyLink'))$('copyLink').onclick=async()=>{const v=$('referralLink')?.textContent;if(!v||v==='Connecting...'||v==='Unavailable'||v==='Refresh page')return;try{await navigator.clipboard.writeText(v);$('copyLink').textContent='Copied!'}catch(e){$('copyLink').textContent='Copy failed'}setTimeout(()=>$('copyLink').textContent='Copy',1200)};
if($('shareReferral'))$('shareReferral').onclick=async()=>{if(!refLink)return;const text='Join me on Marathon Digital Hub: '+refLink;if(navigator.share)try{await navigator.share({title:'Marathon Digital Hub',text,url:refLink})}catch(e){}else{try{await navigator.clipboard.writeText(text);$('shareReferral').textContent='Copied Invite!';setTimeout(()=>$('shareReferral').textContent='↗ Share Invite',1500)}catch(e){}}};
load();